/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Clases.Campus;
import Clases.Edificio;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Maria Eduarda
 */
public class Aula extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aula.class.getName());

    private Campus campus;
    private DefaultTableModel modeloTabla;


    public Aula() {
        initComponents();
        inicializarTabla();
        this.campus = obtenerCampus();
        cargarAulas();
    }

    public Aula(Campus campus) {
        initComponents();
        inicializarTabla();
        this.campus = campus;
        cargarAulas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Agg_Aula = new javax.swing.JButton();
        Buscar_Aula = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Aulas = new javax.swing.JTable();
        Atras = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agg_Aula.setText("Agregar");
        Agg_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agg_AulaActionPerformed(evt);
            }
        });

        Buscar_Aula.setText("Buscar");
        Buscar_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_AulaActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Tabla_Aulas.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Codigo", "Tipo", "Nivel", "Edificio"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Aulas);

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Agg_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(Buscar_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Atras)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Actualizar))))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Agg_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Buscar_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Atras)
                                        .addComponent(Actualizar))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    /**
     * Obtiene un campus con datos de prueba
     */
    private Campus obtenerCampus() {
        Campus campus = new Campus("Campus Principal", 50);

        // Crear edificios
        Edificio biblioteca = new Edificio("Biblioteca", "Calle 1");
        Edificio laboratorios = new Edificio("Laboratorios", "Calle 2");
        Edificio aulasA = new Edificio("Aulas A", "Calle 3");
        Edificio administracion = new Edificio("Administración", "Calle 4");
        Edificio cafeteria = new Edificio("Cafetería", "Calle 5");

        campus.agregarEdificio(biblioteca);
        campus.agregarEdificio(laboratorios);
        campus.agregarEdificio(aulasA);
        campus.agregarEdificio(administracion);
        campus.agregarEdificio(cafeteria);

        // Conectar edificios
        campus.conectarEdificios(biblioteca, laboratorios, 50);
        campus.conectarEdificios(laboratorios, aulasA, 30);
        campus.conectarEdificios(aulasA, administracion, 40);
        campus.conectarEdificios(administracion, cafeteria, 25);
        campus.conectarEdificios(biblioteca, aulasA, 70);
        campus.conectarEdificios(laboratorios, cafeteria, 60);
        campus.conectarEdificios(biblioteca, administracion, 90);

        // Agregar aulas de ejemplo (usando Clases.Aula)
        Clases.Aula aula1 = new Clases.Aula("A101", biblioteca, "1", "Teoria");
        Clases.Aula aula2 = new Clases.Aula("A102", biblioteca, "1", "Teoria");
        Clases.Aula aula3 = new Clases.Aula("L201", laboratorios, "2", "Laboratorio");
        Clases.Aula aula4 = new Clases.Aula("L202", laboratorios, "2", "Laboratorio");
        Clases.Aula aula5 = new Clases.Aula("A301", aulasA, "3", "Teoria");
        Clases.Aula aula6 = new Clases.Aula("S101", administracion, "1", "Seminario");
        Clases.Aula aula7 = new Clases.Aula("C101", cafeteria, "1", "Teoria");

        // Agregar aulas al campus
        campus.agregarAula(aula1);
        campus.agregarAula(aula2);
        campus.agregarAula(aula3);
        campus.agregarAula(aula4);
        campus.agregarAula(aula5);
        campus.agregarAula(aula6);
        campus.agregarAula(aula7);

        // Depuración: Mostrar cuántas aulas hay
        System.out.println("Aulas creadas en obtenerCampus: " + campus.listarTodasLasAulas().size());

        return campus;
    }

    private void inicializarTabla() {
        modeloTabla = (DefaultTableModel) Tabla_Aulas.getModel();
        modeloTabla.setRowCount(0);
    }

    /**
     * Carga todas las aulas en la tabla
     */
    private void cargarAulas() {
        if (campus == null) {
            JOptionPane.showMessageDialog(this, "Error: No hay conexión con el campus");
            return;
        }

        modeloTabla.setRowCount(0);

        try {
            List<Clases.Aula> aulas = campus.listarTodasLasAulas();
            System.out.println("Aulas encontradas en cargarAulas: " + aulas.size());

            if (aulas.isEmpty()) {
                System.out.println("No se encontraron aulas");
                return;
            }

            for (Clases.Aula aula : aulas) {
                Object[] fila = {
                        aula.getCodigo(),
                        aula.getTipo(),
                        aula.getNivel(),
                        aula.getEdificio().getNombre()
                };
                modeloTabla.addRow(fila);
                System.out.println("  - Aula agregada: " + aula.getCodigo());
            }

            System.out.println("Total de filas en tabla: " + modeloTabla.getRowCount());

        } catch (Exception e) {
            System.out.println("Error al cargar aulas: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar aulas: " + e.getMessage());
        }
    }

    private void actualizarTabla() {
        cargarAulas();
    }

    /**
 * Muestra un diálogo para buscar aulas por código parcial
 */
private void buscarAulasPorCodigoParcial() {
    // Crear un panel personalizado para la búsqueda
    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(2, 1, 5, 5));
    
    // Etiqueta instructiva
    javax.swing.JLabel label = new javax.swing.JLabel("Ingrese parte del código del aula a buscar:");
    label.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    panel.add(label);
    
    // Campo de texto para el código
    javax.swing.JTextField txtCodigo = new javax.swing.JTextField(20);
    txtCodigo.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    panel.add(txtCodigo);
    
    // Mostrar el diálogo
    int resultado = JOptionPane.showConfirmDialog(
            this,
            panel,
            "🔍 Buscar Aulas",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );
    
    // Si el usuario presionó OK
    if (resultado == JOptionPane.OK_OPTION) {
        String codigoBuscar = txtCodigo.getText().trim();
        
        // Validar que no esté vacío
        if (codigoBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, ingrese un código de aula.", 
                    "Campo vacío", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Obtener todas las aulas
        List<Clases.Aula> todasLasAulas = campus.listarTodasLasAulas();
        
        // Limpiar la tabla
        modeloTabla.setRowCount(0);
        
        // Filtrar aulas que contengan el código buscado (IGNORANDO MAYÚSCULAS/MINÚSCULAS)
        int contador = 0;
        for (Clases.Aula aula : todasLasAulas) {
            // Usar toLowerCase() en ambas cadenas para ignorar mayúsculas/minúsculas
            if (aula.getCodigo().toLowerCase().contains(codigoBuscar.toLowerCase())) {
                Object[] fila = {
                        aula.getCodigo(),
                        aula.getTipo(),
                        aula.getNivel(),
                        aula.getEdificio().getNombre()
                };
                modeloTabla.addRow(fila);
                contador++;
            }
        }
        
        if (contador > 0) {
            JOptionPane.showMessageDialog(this, 
                    "✅ Se encontraron " + contador + " aula(s) con el código que contiene: " + codigoBuscar, 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                    "❌ No se encontraron aulas con el código que contiene: " + codigoBuscar, 
                    "No encontrado", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    /**
 * Muestra un diálogo para buscar un aula por código
 */
private void buscarAulaPorCodigo() {
    // Crear un panel personalizado para la búsqueda
    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(2, 1, 5, 5));
    
    // Etiqueta instructiva
    javax.swing.JLabel label = new javax.swing.JLabel("Ingrese el código del aula a buscar:");
    label.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    panel.add(label);
    
    // Campo de texto para el código
    javax.swing.JTextField txtCodigo = new javax.swing.JTextField(20);
    txtCodigo.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    panel.add(txtCodigo);
    
    // Mostrar el diálogo
    int resultado = JOptionPane.showConfirmDialog(
            this,
            panel,
            "🔍 Buscar Aula",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );
    
    // Si el usuario presionó OK
    if (resultado == JOptionPane.OK_OPTION) {
        String codigo = txtCodigo.getText().trim();
        
        // Validar que no esté vacío
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, ingrese un código de aula.", 
                    "Campo vacío", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Buscar el aula 
        Clases.Aula aulaEncontrada = null;
        List<Clases.Aula> todasLasAulas = campus.listarTodasLasAulas();
        
        // Recorrer todas las aulas y comparar 
        for (Clases.Aula aula : todasLasAulas) {
            if (aula.getCodigo().equalsIgnoreCase(codigo)) {
                aulaEncontrada = aula;
                break;
            }
        }
        
        // Limpiar la tabla
        modeloTabla.setRowCount(0);
        
        if (aulaEncontrada != null) {
            // Agregar el aula encontrada a la tabla
            Object[] fila = {
                    aulaEncontrada.getCodigo(),
                    aulaEncontrada.getTipo(),
                    aulaEncontrada.getNivel(),
                    aulaEncontrada.getEdificio().getNombre()
            };
            modeloTabla.addRow(fila);
            
            JOptionPane.showMessageDialog(this, 
                    "✅ Aula encontrada: " + codigo, 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                    "❌ No se encontró un aula con el código: " + codigo, 
                    "No encontrado", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
    

    // ========== EVENTOS ==========

    private void Agg_AulaActionPerformed(java.awt.event.ActionEvent evt) {
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del aula:");
        if (codigo == null || codigo.trim().isEmpty()) return;

        // Verificar si el aula ya existe
        Clases.Aula existente = campus.buscarAula(codigo.trim());
        if (existente != null) {
            JOptionPane.showMessageDialog(this, "Error: Ya existe un aula con el código " + codigo.trim());
            return;
        }

        // Obtener lista de edificios
        List<Edificio> edificios = campus.listarEdificios();
        if (edificios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay edificios disponibles. Cree un edificio primero.");
            return;
        }

        // Seleccionar edificio
        String[] nombresEdificios = edificios.stream()
                .map(Edificio::getNombre)
                .toArray(String[]::new);

        String edificioSeleccionado = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el edificio:",
                "Edificio",
                JOptionPane.QUESTION_MESSAGE,
                null,
                nombresEdificios,
                nombresEdificios[0]
        );

        if (edificioSeleccionado == null) return;

        Edificio edificio = campus.buscarEdificioPorNombre(edificioSeleccionado);
        if (edificio == null) {
            JOptionPane.showMessageDialog(this, "Error: Edificio no encontrado");
            return;
        }

        String nivel = JOptionPane.showInputDialog(this, "Ingrese el nivel (ej: 1, 2, 3):");
        if (nivel == null || nivel.trim().isEmpty()) return;

        String tipo = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el tipo de aula:",
                "Tipo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Teoria", "Laboratorio", "Seminario"},
                "Teoria"
        );

        if (tipo == null) return;

        // Crear nueva aula
        Clases.Aula nuevaAula = new Clases.Aula(codigo.trim(), edificio, nivel.trim(), tipo);

        try {
            if (campus.agregarAula(nuevaAula)) {
                JOptionPane.showMessageDialog(this, "Aula agregada correctamente");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error: No se pudo agregar el aula.\n" +
                                "Verifique que el nivel '" + nivel + "' pueda crearse en el edificio.",
                        "Error al agregar aula",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    private void Buscar_AulaActionPerformed(java.awt.event.ActionEvent evt) {
         buscarAulaPorCodigo();
    }

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = Tabla_Aulas.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un aula para modificar");
            return;
        }

        String codigoViejo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        String codigoNuevo = JOptionPane.showInputDialog(this, "Nuevo código (dejar vacío para no cambiar):", codigoViejo);
        if (codigoNuevo != null && codigoNuevo.trim().isEmpty()) {
            codigoNuevo = codigoViejo;
        }

        String nuevoTipo = JOptionPane.showInputDialog(this, "Nuevo tipo (dejar vacío para no cambiar):",
                (String) modeloTabla.getValueAt(filaSeleccionada, 1));
        if (nuevoTipo != null && nuevoTipo.trim().isEmpty()) {
            nuevoTipo = null;
        }

        String nuevoNivel = JOptionPane.showInputDialog(this, "Nuevo nivel (dejar vacío para no cambiar):",
                (String) modeloTabla.getValueAt(filaSeleccionada, 2));
        if (nuevoNivel != null && nuevoNivel.trim().isEmpty()) {
            nuevoNivel = null;
        }

        if (campus.modificarAula(codigoViejo, codigoNuevo, nuevoTipo, nuevoNivel)) {
            JOptionPane.showMessageDialog(this, "Aula modificada correctamente");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudo modificar el aula");
        }
    }

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {
        int filaSeleccionada = Tabla_Aulas.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un aula para eliminar");
            return;
        }

        String codigoAula = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar el aula '" + codigoAula + "'?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            if (campus.eliminarAula(codigoAula)) {
                JOptionPane.showMessageDialog(this, "Aula eliminada correctamente");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar el aula");
            }
        }
    }

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Lista actualizada");
    }

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        // Volver a mostrar la ventana principal
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof Principal) {
                window.setVisible(true);
                window.setLocationRelativeTo(null);
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aula().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agg_Aula;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Buscar_Aula;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTable Tabla_Aulas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}