/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Clases.Campus;
import Clases.Edificio;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Eduarda
 */
public class Edificios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Edificios.class.getName());

    private Campus campus;
    private DefaultTableModel modeloTabla;

    public Edificios() {
        initComponents();
        inicializarTabla();
        // Si no tienes un campus global, crea uno de prueba
        this.campus = obtenerCampus(); // Método para obtener el campus
        cargarEdificios();
    }
    
    // Constructor que recibe el campus (recomendado)
    public Edificios(Campus campus) {
        initComponents();
        inicializarTabla();
        this.campus = campus;
        cargarEdificios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Edificios = new javax.swing.JTable();
        Atras = new javax.swing.JButton();
        Agg_Edif = new javax.swing.JButton();
        Elim_Edif = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lista_Edificios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Lista_Edificios);

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Agg_Edif.setText("Agregar");
        Agg_Edif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agg_EdifActionPerformed(evt);
            }
        });

        Elim_Edif.setText("Eliminar");
        Elim_Edif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elim_EdifActionPerformed(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Actualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agg_Edif, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Elim_Edif, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Actualizar))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Agg_Edif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Elim_Edif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {
        modeloTabla = (DefaultTableModel) Lista_Edificios.getModel();
        modeloTabla.setRowCount(0);
    }
    
    private Campus obtenerCampus() {
        Campus campus = new Campus("Campus Principal", 50);
        
        // Agregar algunos edificios de prueba
        campus.agregarEdificio(new Edificio("Biblioteca", "Calle 1"));
        campus.agregarEdificio(new Edificio("Laboratorios", "Calle 2"));
        campus.agregarEdificio(new Edificio("Aulas A", "Calle 3"));
        campus.agregarEdificio(new Edificio("Administración", "Calle 4"));
        
        return campus;
    }
    
    private void cargarEdificios() {
        if (campus == null) {
            JOptionPane.showMessageDialog(this, "Error: No hay conexión con el campus");
            return;
        }
        
        modeloTabla.setRowCount(0);
        
        java.util.List<Edificio> edificios = campus.listarEdificios();
        
        for (Edificio edificio : edificios) {
            Object[] fila = {
                edificio.getNombre()
            };
            modeloTabla.addRow(fila);
        }
    }
    
    private void actualizarTabla() {
        cargarEdificios();
    }
    
    private void Agg_EdifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agg_EdifActionPerformed
        // Pedir el nombre del edificio
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del edificio:");
        if (nombre != null && !nombre.trim().isEmpty()) {
            Edificio nuevoEdificio = new Edificio(nombre.trim());
            
            if (campus.agregarEdificio(nuevoEdificio)) {
                JOptionPane.showMessageDialog(this, "Edificio agregado correctamente");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo agregar el edificio");
            }
        }
    }//GEN-LAST:event_Agg_EdifActionPerformed

    private void Elim_EdifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elim_EdifActionPerformed
         int filaSeleccionada = Lista_Edificios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un edificio para eliminar");
            return;
        }
        
        String nombreEdificio = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
        Edificio edificioAEliminar = campus.buscarEdificioPorNombre(nombreEdificio);
        
        if (edificioAEliminar != null) {
            int confirmacion = JOptionPane.showConfirmDialog(
                this, 
                "¿Está seguro de eliminar el edificio '" + nombreEdificio + "'?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirmacion == JOptionPane.YES_OPTION) {
                if (campus.eliminarEdificio(edificioAEliminar)) {
                    JOptionPane.showMessageDialog(this, "Edificio eliminado correctamente");
                    actualizarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar el edificio");
                }
            }
        }
    }//GEN-LAST:event_Elim_EdifActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
        // Volver a mostrar la ventana principal
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof Principal) {
                window.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_AtrasActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Lista actualizada");
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Edificios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agg_Edif;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Elim_Edif;
    private javax.swing.JTable Lista_Edificios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
