/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Clases.Campus;
import Clases.Edificio;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.List;

/**
 *
 * @author Maria Eduarda
 */
public class Navegacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Navegacion.class.getName());

    private Campus campus;
    
    /**
     * Creates new form Navegacion
     */
    public Navegacion() {
        initComponents();
        this.campus = obtenerCampusPrueba();
        cargarEdificios();
    }
    
    // Constructor que recibe el campus (recomendado)
    public Navegacion(Campus campus) {
        initComponents();
        this.campus = campus;
        cargarEdificios();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Buscar))
                .addContainerGap())
        );

        jComboBox1.getAccessibleContext().setAccessibleName("Origen:");
        jComboBox2.getAccessibleContext().setAccessibleName("Destino:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ========== MÉTODOS AGREGADOS ==========
    
    /**
     * Obtiene un campus con datos de prueba
     */
     private Campus obtenerCampusPrueba() {
        Campus campus = new Campus("Campus Principal", 50);
        
        // Crear edificios
        Edificio biblioteca = new Edificio("Biblioteca", "Calle 1");
        Edificio laboratorios = new Edificio("Laboratorios", "Calle 2");
        Edificio aulasA = new Edificio("Aulas A", "Calle 3");
        Edificio administracion = new Edificio("Administración", "Calle 4");
        Edificio cafeteria = new Edificio("Cafetería", "Calle 5");
        
        // Agregar edificios al campus
        campus.agregarEdificio(biblioteca);
        campus.agregarEdificio(laboratorios);
        campus.agregarEdificio(aulasA);
        campus.agregarEdificio(administracion);
        campus.agregarEdificio(cafeteria);
        
        // Conectar edificios (crear caminos)
        campus.conectarEdificios(biblioteca, laboratorios, 50);
        campus.conectarEdificios(laboratorios, aulasA, 30);
        campus.conectarEdificios(aulasA, administracion, 40);
        campus.conectarEdificios(administracion, cafeteria, 25);
        campus.conectarEdificios(biblioteca, aulasA, 70);
        campus.conectarEdificios(laboratorios, cafeteria, 60);
        campus.conectarEdificios(biblioteca, administracion, 90);
        
        return campus;
    }
    
    /**
     * Carga los edificios en los combobox
     */
    private void cargarEdificios() {
        if (campus == null) {
            JOptionPane.showMessageDialog(this, "Error: No hay conexión con el campus");
            return;
        }
        
        List<Edificio> edificios = campus.listarEdificios();
        
        // Crear modelos para los combobox
        DefaultComboBoxModel<String> modelOrigen = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> modelDestino = new DefaultComboBoxModel<>();
        
        for (Edificio edificio : edificios) {
            modelOrigen.addElement(edificio.getNombre());
            modelDestino.addElement(edificio.getNombre());
        }
        
        jComboBox1.setModel(modelOrigen);
        jComboBox2.setModel(modelDestino);
    }
    
    /**
     * Calcula y muestra la ruta mínima entre dos edificios
     */
    private void calcularRuta() {
        String nombreOrigen = (String) jComboBox1.getSelectedItem();
        String nombreDestino = (String) jComboBox2.getSelectedItem();
        
        // Validaciones
        if (nombreOrigen == null || nombreDestino == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un edificio de origen y destino");
            return;
        }
        
        if (nombreOrigen.equals(nombreDestino)) {
            JOptionPane.showMessageDialog(this, "El origen y destino no pueden ser iguales");
            return;
        }
        
        // Buscar los edificios
        Edificio origen = campus.buscarEdificioPorNombre(nombreOrigen);
        Edificio destino = campus.buscarEdificioPorNombre(nombreDestino);
        
        if (origen == null || destino == null) {
            JOptionPane.showMessageDialog(this, "Edificio no encontrado");
            return;
        }
        
        // Calcular la ruta
        List<Edificio> ruta = campus.rutaMasCortaEntreEdificios(origen, destino);
        int distancia = campus.distanciaEntreEdificios(origen, destino);
        
        // Construir el resultado
        StringBuilder resultado = new StringBuilder();
        resultado.append("=".repeat(50)).append("\n");
        resultado.append("            RUTA MÍNIMA\n");
        resultado.append("=".repeat(50)).append("\n\n");
        resultado.append("📍 Origen:  ").append(nombreOrigen).append("\n");
        resultado.append("📍 Destino: ").append(nombreDestino).append("\n");
        resultado.append("📏 Distancia total: ").append(distancia).append(" metros\n\n");
        
        if (ruta == null || ruta.isEmpty()) {
            resultado.append("❌ No hay ruta disponible entre estos edificios.");
        } else {
            resultado.append("🗺️ Camino:\n");
            for (int i = 0; i < ruta.size(); i++) {
                resultado.append("   ");
                if (i == 0) {
                    resultado.append("🚪 ");
                } else if (i == ruta.size() - 1) {
                    resultado.append("🏁 ");
                } else {
                    resultado.append("•  ");
                }
                resultado.append(ruta.get(i).getNombre());
                
                // Mostrar distancia entre cada par
                if (i < ruta.size() - 1) {
                    Edificio actual = ruta.get(i);
                    Edificio siguiente = ruta.get(i + 1);
                    int distParcial = campus.getRedCampus().getPeso(actual, siguiente);
                    resultado.append("\n       ↓ ").append(distParcial).append("m\n");
                }
            }
            resultado.append("\n\n✅ Ruta calculada exitosamente.");
        }
        
        // Mostrar en el área de texto
        jTextArea1.setText(resultado.toString());
        // Mover el cursor al inicio
        jTextArea1.setCaretPosition(0);
    }


    // ========== EVENTOS ==========  
    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
        // Volver a mostrar la ventana principal
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof Principal) {
                window.setVisible(true);
                window.setLocationRelativeTo(null);
                break;
            }
        }
    }//GEN-LAST:event_AtrasActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        calcularRuta();
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Navegacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
