/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales;

import Clases.Campus;
import Clases.Edificio;

/**
 *
 * @author Maria Eduarda
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

   private Campus obtenerCampus() {
    Campus campus = new Campus("Campus Principal", 50);
    
    Edificio biblioteca = new Edificio("Biblioteca", "Calle 1");
    Edificio laboratorios = new Edificio("Laboratorios", "Calle 2");
    Edificio aulasA = new Edificio("Aulas A", "Calle 3");
    Edificio administracion = new Edificio("Administración", "Calle 4");
    Edificio cafeteria = new Edificio("Cafetería", "Calle 5");
    
    campus.agregarEdificio(biblioteca);
    campus.agregarEdificio(laboratorios);
    campus.agregarEdificio(aulasA);
    campus.agregarEdificio(administracion);
    campus.agregarEdificio(cafeteria);
    
    campus.conectarEdificios(biblioteca, laboratorios, 50);
    campus.conectarEdificios(laboratorios, aulasA, 30);
    campus.conectarEdificios(aulasA, administracion, 40);
    campus.conectarEdificios(administracion, cafeteria, 25);
    campus.conectarEdificios(biblioteca, aulasA, 70);
    campus.conectarEdificios(laboratorios, cafeteria, 60);
    
    return campus;
} 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Edificios = new javax.swing.JButton();
        Aulas = new javax.swing.JButton();
        Navegacion = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Foto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Edificios.setText("Gestion de Edificios");
        Edificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificiosActionPerformed(evt);
            }
        });

        Aulas.setText("Gestion de Aulas");
        Aulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulasActionPerformed(evt);
            }
        });

        Navegacion.setText("Navegacion");
        Navegacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavegacionActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visuales/3a266c524f7e831f33c3765bff7afcb7.jpg"))); // NOI18N
        Foto.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setText("Campus Universitario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Aulas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edificios, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Edificios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Aulas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(Foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificiosActionPerformed
        this.setVisible(false);     
        Edificios ventanaEdificios = new Edificios();
        ventanaEdificios.setVisible(true);
        ventanaEdificios.setLocationRelativeTo(null);
    }//GEN-LAST:event_EdificiosActionPerformed

    private void AulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulasActionPerformed
        this.setVisible(false);
        Aula ventanaAulas = new Aula();
        ventanaAulas.setVisible(true);
        ventanaAulas.setLocationRelativeTo(null);
    }//GEN-LAST:event_AulasActionPerformed

    private void NavegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavegacionActionPerformed
     this.setVisible(false);
    Campus campus = obtenerCampus(); // O usa el que ya tengas
    Navegacion ventanaNavegacion = new Navegacion(campus);
    ventanaNavegacion.setVisible(true);
    ventanaNavegacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_NavegacionActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    this.setVisible(false);
    this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        Principal ventana = new Principal();
        ventana.setLocationRelativeTo(null); 
        ventana.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aulas;
    private javax.swing.JButton Edificios;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Foto;
    private javax.swing.JButton Navegacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
